version: "3.8"

volumes:
  rabbitmq_data:

services:
 
  ###################################
  # Review: The Review microservice
  ###################################
  Review:
    build:
      context: ./
      dockerfile: Review.Dockerfile
    image: timothyczh/review:Project
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/Review
      PYTHONUNBUFFERED: 1
 