version: "3.8"

volumes:
  rabbitmq_data:

services:
  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: itinerary
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq

  ###################################
  # Notification: The Notification microservice
  ###################################
  notification:
    build:
      context: ./
      dockerfile: ./notification/notification.Dockerfile
    image: elginrspx/notification:itinerary
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1

  ###################################
  # Itinerary Approval: The Itinerary Approval complex microservice
  ###################################
  itinerary_approval:
    build:
      context: ./
      dockerfile: ./itinerary_approval/itinerary_approval.Dockerfile
    image: elginrspx/itinerary_approval:itinerary
    restart: always
    depends_on:
      - rabbitmq
      - notification
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
    ports:
      - "5100:5100"

  ###################################
  # Purchase Itinerary: The Purchase Itinerary complex microservice
  ###################################
  purchase_itinerary:
    build:
      context: ./
      dockerfile: ./purchase_itinerary/purchase_itinerary.Dockerfile
    image: elginrspx/purchase_itinerary:itinerary
    restart: always
    depends_on:
      - rabbitmq
      - notification
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      PYTHONUNBUFFERED: 1
    ports:
      - "5300:5300"